"""add is_blog column to Blog model fr this time

Revision ID: 17d9f6235d8c
Revises: c34fc75b1ab1
Create Date: 2026-07-01 00:13:36.875854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d9f6235d8c'
down_revision: Union[str, Sequence[str], None] = 'c34fc75b1ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'is_blog',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'is_blog',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
