"""add is_blog column to blog model

Revision ID: c34fc75b1ab1
Revises: a4ab35f6fff4
Create Date: 2026-06-30 23:50:54.363001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34fc75b1ab1'
down_revision: Union[str, Sequence[str], None] = 'a4ab35f6fff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
