"""change user_id to username

Revision ID: f4abaa02f7d8
Revises: 0001
Create Date: 2026-07-17 17:09:09.863752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4abaa02f7d8'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_table', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('api_table', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_table', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('api_table', 'username')
    # ### end Alembic commands ###
